# Generated by Django 5.0.3 on 2024-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcare', '0002_aptionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petName',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Hamster', 'Hamster'), ('Duck', 'Duck'), ('Other', 'Other')], max_length=100),
        ),
    ]
